name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Cloning repository
          uses: actions/checkout@v1

        - name: Docker Login
          uses: azure/docker-login@v1
          with:
            login-server: ghcr.io
            username: $GITHUB_ACTOR
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker Build
          run: |
            DOCKER_TAG=$(echo ${GITHUB_REF_NAME} | sed -e 's/\//-/g' | sed -e 's/[A-Z]/\L&/g')
            docker build -t ghcr.io/pchalamet/gh-actions-explorer:${DOCKER_TAG} --build-arg config=Release .
            docker push ghcr.io/pchalamet/gh-actions-explorer:${DOCKER_TAG}

    deploy:
      uses: pchalamet/gh-actions-explorer/.github/workflows/deploy.yml@master
      with:
            label: ${{ github.ref_name }}
            label-type: $${ github.ref_type }}
