name: build

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Cloning repository
          uses: actions/checkout@v1

        - name: Docker Login
          uses: azure/docker-login@v1
          with:
            login-server: ghcr.io
            username: $GITHUB_ACTOR
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker Build
          run: |
            DOCKER_TAG=$(echo ${GITHUB_REF_NAME} | sed -e 's/\//-/g' | sed -e 's/[A-Z]/\L&/g')
            docker build -t ghcr.io/pchalamet/gh-actions-explorer:${DOCKER_TAG} --build-arg config=Release .
            docker push ghcr.io/pchalamet/gh-actions-explorer:${DOCKER_TAG}

    plan:
        runs-on: ubuntu-latest
        env:
            working-directory: Deployment

        steps:
          - uses: actions/checkout@v2
          - uses: hashicorp/setup-terraform@v1

          - run: terraform init
            working-directory: ${{ env.working-directory }}

          - run: terraform plan -out=dev.planfile
            working-directory: ${{ env.working-directory }}

          - name: Upload artifacts
            uses: actions/upload-artifact@v2
            with:
              name: planfiles
              path: Deployment/*.planfile

    deploy-dev:
        runs-on: ubuntu-latest
        env:
            working-directory: Deployment
        environment: dev
        needs: plan

        steps:
          - uses: actions/checkout@v2
          - uses: hashicorp/setup-terraform@v1
          - uses: hashicorp/setup-terraform@v1

          - uses: actions/download-artifact@v2
            with:
              name: planfiles
              path: ${{ env.working-directory }}

          - run: terraform init
            working-directory: ${{ env.working-directory }}

          - run: terraform apply -auto-approve dev.planfile 
            working-directory: ${{ env.working-directory }}
