name: deploy

on:
    workflow_call:
        inputs:
            label:
                description: 'Tag to deploy'
                default: 'master'
                required: type
                type: string
            label-type:
                description: 'Type of label'
                default: 'branch'
                required: type
                type: string

jobs:
    plan:
        runs-on: ubuntu-latest
        env:
            working-directory: Deployment

        steps:
          - uses: actions/checkout@v2
          - uses: hashicorp/setup-terraform@v1

          - run: |
                echo "${{ github.event.inputs.label}}"
                echo "${{ github.event.inputs.label-type}}"

          - run: terraform init
            working-directory: ${{ env.working-directory }}

          - run: terraform plan -out=dev.planfile
            working-directory: ${{ env.working-directory }}

          - name: Upload artifacts
            uses: actions/upload-artifact@v2
            with:
              name: planfiles
              path: Deployment/*.planfile

    deploy-dev:
        runs-on: ubuntu-latest
        env:
            working-directory: Deployment
        environment: dev
        needs: plan

        steps:
          - uses: actions/checkout@v2
          - uses: hashicorp/setup-terraform@v1
          - uses: hashicorp/setup-terraform@v1

          - uses: actions/download-artifact@v2
            with:
              name: planfiles
              path: ${{ env.working-directory }}

          - run: terraform init
            working-directory: ${{ env.working-directory }}

          - run: terraform apply -auto-approve dev.planfile 
            working-directory: ${{ env.working-directory }}

    deploy-prod:
        runs-on: ubuntu-latest
        if: github.ref_type == 'tag'
        environment: prod
        needs: plan

        steps:
          - name: deploy
            run: echo "deploying to prod"
