name: deploy

on: [push]

jobs:
    plan:
        runs-on: ubuntu-latest
        if: github.ref_type == 'tag'
        needs: dump-variables

        steps:
          - name: deploy
            run: echo "planning to dev"

    deploy-dev:
        runs-on: ubuntu-latest
        if: github.ref_type == 'tag'
        environment: dev
        needs: dump-variables

        steps:
          - name: deploy
            run: echo "deploying to dev"

    deploy-prod:
        runs-on: ubuntu-latest
        if: github.ref_type == 'tag'
        environment: prod
        needs: dump-variables

        steps:
          - name: deploy
            run: echo "deploying to prod"
